/*!
* artDialog 5 plugins
* Date: 2012-03-16
* https://github.com/aui/artDialog
* (c) 2009-2012 TangBin, http://www.planeArt.cn
*
* This is licensed under the GNU LGPL, version 2.1 or later.
* For details, see: http://creativecommons.org/licenses/LGPL/2.1/
*/
(function(a){a.alert=a.dialog.alert=function(b,c){return a.dialog({id:"Alert",fixed:!0,lock:!0,content:b,ok:!0,beforeunload:c})},a.confirm=a.dialog.confirm=function(b,c,d){return a.dialog({id:"Confirm",fixed:!0,lock:!0,content:b,ok:c,cancel:d})},a.prompt=a.dialog.prompt=function(b,c,d){d=d||"";var e;return a.dialog({id:"Prompt",fixed:!0,lock:!0,content:['<div style="margin-bottom:5px;font-size:12px">',b,"</div>","<div>",'<input type="text" class="d-input-text" value="',d,'" style="width:18em;padding:6px 4px" />',"</div>"].join(""),initialize:function(){e=this.dom.content.find(".d-input-text")[0],e.select(),e.focus()},ok:function(){return c&&c.call(this,e.value)},cancel:function(){}})},a.dialog.prototype.shake=function(){var a=function(a,b,c){var d=+(new Date),e=setInterval(function(){var f=+(new Date)-d,g=f/c;g>=1?(clearInterval(e),b(g)):a(g)},13)},b=function(c,d,e){var f=arguments[3];f===undefined&&(f=6,e/=f);var g=c.style,h=parseInt(g.marginLeft)||0;a(function(a){c.style.marginLeft=h+(d-h)*a+"px"},function(){f!==0&&b(c,f===1?0:(d/f-d)*1.3,e,--f)},e)};return function(){return b(this.dom.wrap[0],40,600),this}}();var b=function(){var a=this,b=function(b){var c=a[b];a[b]=function(){return c.apply(a,arguments)}};b("start"),b("over"),b("end")};b.prototype={start:function(b){return a(document).bind("mousemove",this.over).bind("mouseup",this.end),this.x=b.clientX,this.y=b.clientY,this.onstart(b.clientX,b.clientY),!1},over:function(a){return this.onover(a.clientX-this.x,a.clientY-this.y),!1},end:function(b){return a(document).unbind("mousemove",this.over).unbind("mouseup",this.end),this.onend(b.clientX,b.clientY),!1}};var c=a(window),d=a(document),e=document.documentElement,f=!("minWidth"in e.style),g=!f&&"onlosecapture"in e,h="setCapture"in e,i=function(){return!1},j=function(a){var e=new b,f=artDialog.focus,j=f.dom,k=j.wrap,l=j.title,m=j.main,n=k[0],o=l[0],p=m[0],q=n.style,r=p.style,s=a.target===j.se[0]?!0:!1,t=n.style.position==="fixed",u=t?0:d.scrollLeft(),v=t?0:d.scrollTop(),w=c.width()-n.offsetWidth+u,x=c.height()-n.offsetHeight+v,y,z,A,B;e.onstart=function(a,b){s?(y=p.offsetWidth,z=p.offsetHeight):(A=n.offsetLeft,B=n.offsetTop),d.bind("dblclick",e.end).bind("dragstart",i),g?l.bind("losecapture",e.end):c.bind("blur",e.end),h&&o.setCapture(),k.addClass("d-state-drag"),f.focus()},e.onover=function(a,b){if(s){var c=a+y,d=b+z;q.width="auto",r.width=Math.max(0,c)+"px",q.width=n.offsetWidth+"px",r.height=Math.max(0,d)+"px"}else{var e=Math.max(u,Math.min(w,a+A)),f=Math.max(v,Math.min(x,b+B));q.left=e+"px",q.top=f+"px"}},e.onend=function(a,b){d.unbind("dblclick",e.end).unbind("dragstart",i),g?l.unbind("losecapture",e.end):c.unbind("blur",e.end),h&&o.releaseCapture(),k.removeClass("d-state-drag")},e.start(a)};a(document).bind("mousedown",function(a){var b=artDialog.focus;if(!b)return;var c=a.target,d=b.config,e=b.dom;if(d.drag!==!1&&c===e.title[0]||d.resize!==!1&&c===e.se[0])return j(a),!1})})(this.art||this.jQuery)